import{useState}from'react';import{useAuth}from'../context/AuthContext';import AppShell from'../components/AppShell';import toast from'react-hot-toast';import{Zap,ArrowRight,TrendingUp,Briefcase,Target,AlertCircle}from'lucide-react';
function Ring({score,color='#2B9E96',size=110}){const r=42,c=size/2,circ=2*Math.PI*r,off=circ-(score/100)*circ;return<div className="ring-w" style={{width:size,height:size}}><svg width={size} height={size} viewBox={'0 0 '+size+' '+size} style={{transform:'rotate(-90deg)'}}><circle cx={c} cy={c} r={r} fill="none" stroke="var(--cream2)" strokeWidth={7}/><circle cx={c} cy={c} r={r} fill="none" stroke={color} strokeWidth={7} strokeDasharray={circ} strokeDashoffset={off} strokeLinecap="round" style={{transition:'stroke-dashoffset 1.2s ease'}}/></svg><div className="ring-c"><div style={{fontWeight:900,fontSize:size*.22,color,lineHeight:1}}>{score}</div><div style={{fontSize:10,color:'var(--muted2)',marginTop:-1}}>/ 100</div></div></div>;}
const PC=['#2B9E96','#E8601A','#7B6CF6'];
export default function Analyze(){
  const{user,api,updateUser}=useAuth();const[f,setF]=useState({background:user?.background||'',goal:user?.goal||'',city:user?.city||'',currentSkills:''});const[loading,setLoading]=useState(false);const[result,setResult]=useState(user?.skillAnalysis||null);const[proto,setProto]=useState(false);const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const run=async()=>{if(!f.background||!f.goal)return toast.error('Fill in background and career goal.');setLoading(true);try{const data=await api('/analyze',{method:'POST',body:f});setResult(data.analysis);setProto(!!data.prototypeMode);updateUser({...user,xp:data.xp,badges:data.badges,skillAnalysis:data.analysis,background:f.background,goal:f.goal,city:f.city});toast.success('Analysis complete! +50 XP 🎯');}catch(err){toast.error(err.message);}finally{setLoading(false);}};
  return<AppShell><div style={{maxWidth:900}}>
    <div className="fu" style={{marginBottom:24}}><div className="eye"><Zap size={11}/>AI Skill Scanner</div><h2 style={{fontSize:24,fontWeight:900,letterSpacing:'-.03em',marginBottom:4}}>Know exactly where you stand.</h2><p style={{color:'var(--muted)',fontSize:14}}>AI analyses your profile against India's live job market in seconds.</p></div>
    {!result?<div className="card fu1" style={{boxShadow:'0 4px 20px rgba(0,0,0,0.06)'}}><div style={{display:'grid',gap:16}}><div><label className="lbl">Your background *</label><textarea className="inp" placeholder="e.g. 2nd year B.Com student in Jaipur" value={f.background} onChange={e=>set('background',e.target.value)}/></div><div><label className="lbl">Career goal *</label><input className="inp" placeholder="e.g. Data Analyst at a startup in 6 months" value={f.goal} onChange={e=>set('goal',e.target.value)}/></div><div className="g2" style={{gap:14}}><div><label className="lbl">City</label><input className="inp" placeholder="Jaipur" value={f.city} onChange={e=>set('city',e.target.value)}/></div><div><label className="lbl">Skills you have</label><input className="inp" placeholder="Excel, basic Python..." value={f.currentSkills} onChange={e=>set('currentSkills',e.target.value)}/></div></div><button className="btn btn-orange" onClick={run} disabled={loading} style={{width:'fit-content'}}>{loading?<><div className="spinner" style={{borderTopColor:'white'}}/>Analysing...</>:<><Zap size={15}/>Run AI Skill Scan</>}</button></div></div>
    :<div style={{display:'flex',flexDirection:'column',gap:20}}>
      {proto&&<div style={{display:'flex',alignItems:'center',gap:10,padding:'10px 14px',background:'rgba(245,200,66,0.1)',borderRadius:10,border:'1px solid rgba(245,200,66,0.25)',fontSize:13,color:'#7A6000'}}><AlertCircle size={14}/>Prototype mode — <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer" style={{fontWeight:800,color:'var(--orange)',textDecoration:'underline'}}>Add a free Gemini key</a> for live AI.</div>}
      <div className="card card-teal fu" style={{display:'flex',gap:28,alignItems:'center',flexWrap:'wrap',boxShadow:'0 4px 20px rgba(0,0,0,0.06)'}}><Ring score={result.matchScore}/><div style={{flex:1}}><div className="chip chip-t" style={{marginBottom:9}}>Market Match Score</div><h3 style={{fontSize:18,fontWeight:900,letterSpacing:'-.02em',marginBottom:5}}>{result.marketInsight}</h3><p style={{color:'var(--muted)',fontSize:13,marginBottom:10}}>Expected in 1 year: <strong style={{color:'var(--teal)'}}>{result.salaryRange}</strong></p><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><span className="chip chip-t">Readiness {result.readinessScore}/100</span><span className="chip chip-o">+50 XP</span></div></div><button className="btn btn-outline btn-sm" onClick={()=>setResult(null)}>Re-scan</button></div>
      <div className="fu1"><div style={{fontWeight:800,fontSize:16,letterSpacing:'-.01em',marginBottom:13,display:'flex',alignItems:'center',gap:7}}><Target size={16} color="var(--teal)"/>Build these 3 skills next</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{result.top3Skills?.map((s,i)=><div key={s.skill} className="card" style={{display:'flex',gap:14,borderLeft:'3px solid '+PC[i],boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}}><div style={{width:30,height:30,borderRadius:8,background:PC[i]+'14',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:13,color:PC[i],flexShrink:0}}>{i+1}</div><div style={{flex:1}}><div style={{fontWeight:800,marginBottom:3,letterSpacing:'-.01em'}}>{s.skill}</div><p style={{fontSize:13,color:'var(--muted)',marginBottom:7,lineHeight:1.5}}>{s.reason}</p><div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{s.resources?.map(r=><span key={r} className="chip" style={{fontSize:11}}>{r}</span>)}</div></div></div>)}</div></div>
      <div className="fu2"><div style={{fontWeight:800,fontSize:16,letterSpacing:'-.01em',marginBottom:13,display:'flex',alignItems:'center',gap:7}}><Briefcase size={16} color="var(--orange)"/>Best roles for you</div><div className="g2" style={{gap:12}}>{result.topRoles?.map(r=><div key={r.title} className="card" style={{padding:'15px 18px',boxShadow:'0 2px 8px rgba(0,0,0,0.04)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:8}}><div style={{fontWeight:800,fontSize:14,letterSpacing:'-.01em'}}>{r.title}</div><span className="chip chip-t" style={{fontSize:11,flexShrink:0}}>{r.match}%</span></div><div style={{display:'flex',gap:5,flexWrap:'wrap'}}><span className="chip" style={{fontSize:11}}>💰 {r.avgSalary}</span><span className="chip" style={{fontSize:11}}>📋 {r.openings}</span><span className={'chip '+(r.demand==='High'?'chip-g':r.demand==='Medium'?'chip-t':'chip-o')} style={{fontSize:11}}>{r.demand}</span></div></div>)}</div></div>
      <div className="fu3"><div style={{fontWeight:800,fontSize:16,letterSpacing:'-.01em',marginBottom:13,display:'flex',alignItems:'center',gap:7}}><TrendingUp size={16} color="var(--purple)"/>Skill gaps to close</div><div style={{display:'flex',flexDirection:'column',gap:8}}>{result.skillGaps?.map(g=><div key={g.skill} className="card" style={{padding:'13px 17px',display:'flex',alignItems:'center',gap:12,flexWrap:'wrap',boxShadow:'0 2px 8px rgba(0,0,0,0.04)'}}><div style={{flex:1}}><div style={{fontWeight:800,marginBottom:2,letterSpacing:'-.01em'}}>{g.skill}</div><div style={{fontSize:12.5,color:'var(--muted)'}}>{g.whyItMatters}</div></div><div style={{display:'flex',gap:6,flexShrink:0}}><span className={'chip '+(g.priority==='High'?'chip-o':g.priority==='Medium'?'chip-t':'chip-g')} style={{fontSize:11}}>{g.priority}</span><span className="chip" style={{fontSize:11}}>⏱ {g.timeToLearn}</span></div></div>)}</div></div>
      <div className="fu4" style={{display:'flex',gap:10}}><a href="/roadmap" className="btn btn-orange"><ArrowRight size={15}/>Get 90-Day Roadmap</a><button className="btn btn-outline" onClick={()=>setResult(null)}>Re-scan</button></div>
    </div>}
  </div></AppShell>;
}
