import{useState,useEffect}from'react';import{useAuth}from'../context/AuthContext';import AppShell from'../components/AppShell';import{Award,Trophy}from'lucide-react';
export default function Badges(){
  const{user,api}=useAuth();const[badges,setBadges]=useState([]);const[board,setBoard]=useState([]);const[tab,setTab]=useState('badges');
  useEffect(()=>{Promise.all([api('/badges'),api('/leaderboard')]).then(([b,l])=>{setBadges(b);setBoard(l);}).catch(()=>{});},[]);
  const level=Math.floor((user?.xp||0)/100)+1;const pct=(user?.xp||0)%100;const earned=badges.filter(b=>b.earned).length;
  return<AppShell><div style={{maxWidth:900}}>
    <div className="fu" style={{marginBottom:24}}><div className="eye"><Award size={11}/>Badges & XP</div><h2 style={{fontSize:24,fontWeight:900,letterSpacing:'-.03em',marginBottom:4}}>Your progress, tracked.</h2><p style={{color:'var(--muted)',fontSize:14}}>Every action earns XP. Every milestone unlocks a badge.</p></div>
    <div className="card fu1" style={{marginBottom:22,boxShadow:'0 4px 16px rgba(0,0,0,0.06)',background:'linear-gradient(135deg,rgba(43,158,150,0.04),rgba(232,96,26,0.04))'}}>
      <div style={{display:'flex',gap:28,flexWrap:'wrap',alignItems:'center'}}>
        <div><div style={{fontSize:10,color:'var(--muted2)',fontWeight:900,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:5}}>Current Level</div><div style={{fontFamily:'Instrument Serif,Georgia,serif',fontWeight:700,fontSize:52,lineHeight:1,color:'var(--teal)',letterSpacing:'-.04em',fontStyle:'italic'}}>{level}</div></div>
        <div style={{flex:1}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8,fontSize:13}}><span style={{color:'var(--muted)',fontWeight:700}}>Level {level} → {level+1}</span><span style={{fontWeight:900,color:'var(--teal)'}}>{user?.xp||0} XP total</span></div><div className="xp-track" style={{height:8}}><div className="xp-fill" style={{width:pct+'%'}}/></div><div style={{fontSize:12,color:'var(--muted2)',marginTop:5}}>{100-pct} XP to Level {level+1}</div></div>
        <div style={{display:'flex',gap:22}}><div style={{textAlign:'center'}}><div style={{fontFamily:'Instrument Serif,Georgia,serif',fontSize:28,fontWeight:700,color:'var(--orange)',fontStyle:'italic'}}>{earned}</div><div style={{fontSize:12,color:'var(--muted)'}}>Earned</div></div><div style={{textAlign:'center'}}><div style={{fontFamily:'Instrument Serif,Georgia,serif',fontSize:28,fontWeight:700,color:'var(--purple)',fontStyle:'italic'}}>{badges.length}</div><div style={{fontSize:12,color:'var(--muted)'}}>Total</div></div></div>
      </div>
    </div>
    <div className="card fu2" style={{marginBottom:22,padding:'16px 20px',boxShadow:'0 2px 8px rgba(0,0,0,0.04)'}}><div style={{fontWeight:800,fontSize:14,letterSpacing:'-.01em',marginBottom:10}}>How to earn XP</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{[['AI Skill Scan','+50 XP','chip-t'],['Generate Roadmap','+30 XP','chip-o'],['AI Mentor Chat','+5 XP','chip-gold'],['Upload Avatar','+10 XP','chip-p'],['7-day streak','+100 XP','chip-g']].map(([a,x,cls])=><div key={a} style={{display:'flex',alignItems:'center',gap:7,padding:'5px 12px',background:'var(--cream2)',borderRadius:100,border:'1px solid var(--border)'}}><span style={{fontSize:13}}>{a}</span><span className={'chip '+cls} style={{fontSize:10,padding:'2px 8px'}}>{x}</span></div>)}</div></div>
    <div style={{display:'flex',gap:3,marginBottom:22,background:'var(--white)',padding:4,borderRadius:100,width:'fit-content',border:'1px solid var(--border)',boxShadow:'0 2px 8px rgba(0,0,0,0.04)'}}>{[['badges','🏅 Badges'],['leaderboard','🏆 Leaderboard']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{padding:'7px 20px',borderRadius:100,border:'none',cursor:'pointer',fontSize:13,fontWeight:800,fontFamily:'Cabinet Grotesk,system-ui',transition:'all .2s',background:tab===id?'var(--ink)':'transparent',color:tab===id?'white':'var(--muted)'}}>{label}</button>)}</div>
    {tab==='badges'&&<div className="g3 fu" style={{gap:14}}>{badges.length===0?[1,2,3,4,5,6].map(i=><div key={i} className="card" style={{height:180,animation:'pulse 1.5s ease infinite',background:'var(--cream2)'}}/>):badges.map(b=><div key={b.id} className="card" style={{textAlign:'center',opacity:b.earned?1:0.38,position:'relative',transition:'all .3s cubic-bezier(.34,1.56,.64,1)',boxShadow:'0 2px 10px rgba(0,0,0,0.05)',cursor:'default'}} onMouseEnter={e=>{if(b.earned){e.currentTarget.style.transform='translateY(-6px) scale(1.02)';e.currentTarget.style.boxShadow='0 12px 28px rgba(0,0,0,0.1)';}}} onMouseLeave={e=>{e.currentTarget.style.transform='';e.currentTarget.style.boxShadow='0 2px 10px rgba(0,0,0,0.05)';}}>
      {b.earned&&<div style={{position:'absolute',top:10,right:10}}><span className="chip chip-t" style={{fontSize:10}}>Earned</span></div>}
      <div style={{fontSize:38,marginBottom:10,filter:b.earned?'none':'grayscale(1)'}}>{b.icon}</div>
      <div style={{fontWeight:900,fontSize:14,letterSpacing:'-.01em',marginBottom:5}}>{b.name}</div>
      <p style={{fontSize:12.5,color:'var(--muted)',marginBottom:9,lineHeight:1.4}}>{b.desc}</p>
      <span className={'chip '+(b.earned?'chip-t':'')} style={{fontSize:11}}>+{b.xp} XP</span>
    </div>)}</div>}
    {tab==='leaderboard'&&<div className="card fu" style={{boxShadow:'0 4px 16px rgba(0,0,0,0.06)'}}><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em',marginBottom:18,display:'flex',alignItems:'center',gap:7}}><Trophy size={17} color="var(--yellow)"/>Top Learners</div>
      {board.length===0?<div style={{textAlign:'center',padding:'48px 0',color:'var(--muted2)'}}><div style={{fontSize:36,marginBottom:10}}>🥇</div><div style={{fontSize:14,fontWeight:700}}>Be the first!</div><div style={{fontSize:13,marginTop:4,color:'var(--muted)'}}>Run AI Skill Scan to earn XP and claim the top spot.</div></div>
      :board.map((u,i)=><div key={i} style={{display:'flex',alignItems:'center',gap:13,padding:'12px 0',borderBottom:i<board.length-1?'1px solid var(--border)':'none'}}>
        <div style={{width:28,textAlign:'center',fontWeight:900,fontSize:14,color:i===0?'#F5C842':i===1?'#A0A0A0':i===2?'#CD7F32':'var(--muted2)'}}>{i===0?'🥇':i===1?'🥈':i===2?'🥉':'#'+(i+1)}</div>
        {u.avatar?<div style={{width:34,height:34,borderRadius:'50%',overflow:'hidden',border:'2px solid var(--teal)',flexShrink:0}}><img src={u.avatar} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>:<div style={{width:34,height:34,borderRadius:'50%',background:'linear-gradient(135deg,var(--teal),var(--orange))',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:14,color:'white',flexShrink:0}}>{u.name[0].toUpperCase()}</div>}
        <div style={{flex:1}}><div style={{fontWeight:800,fontSize:14,letterSpacing:'-.01em'}}>{u.name}</div><div style={{fontSize:12,color:'var(--muted)'}}>{u.city} · Level {u.level} · {u.badges} badges</div></div>
        <span className="chip chip-t" style={{fontWeight:900,flexShrink:0}}>{u.xp} XP</span>
      </div>)}
    </div>}
  </div></AppShell>;
}
