import{useNavigate}from'react-router-dom';import{useAuth}from'../context/AuthContext';import AppShell from'../components/AppShell';import HQExplorer from'../components/HQExplorer';import{Zap,Map,TrendingUp,MessageSquare,Award,ArrowRight,ChevronRight}from'lucide-react';
const TIPS=['Python is the #1 skill in demand — 180K+ open jobs right now.','Students with a real portfolio earn 40% more than those without.','NPTEL certificates are free, recognised by 200+ companies.','Starting salary for Data Analysts in Jaipur: ₹4-8 LPA.','Communication is the most underrated skill — unlocks every senior role.'];
const QUICK=[{icon:Zap,color:'#E8601A',bg:'rgba(232,96,26,0.08)',label:'AI Skill Scan',desc:'See your market fit score',path:'/analyze',hot:true},{icon:Map,color:'#7B6CF6',bg:'rgba(123,108,246,0.08)',label:'90-Day Plan',desc:'Get your personalised roadmap',path:'/roadmap'},{icon:TrendingUp,color:'#2B9E96',bg:'rgba(43,158,150,0.08)',label:'Market Intel',desc:'Live salary and demand data',path:'/market'},{icon:MessageSquare,color:'#F5C842',bg:'rgba(245,200,66,0.12)',label:'AI Mentor',desc:'Ask anything, India-specific tips',path:'/chat'}];
export default function Dashboard(){
  const{user}=useAuth();const nav=useNavigate();const tip=TIPS[new Date().getDate()%TIPS.length];const level=Math.floor((user?.xp||0)/100)+1;const pct=(user?.xp||0)%100;const hr=new Date().getHours();const greet=hr<12?'Good morning':hr<17?'Good afternoon':'Good evening';
  return<AppShell><div style={{maxWidth:920}}>
    <div className="fu" style={{marginBottom:28}}><p style={{fontSize:13,color:'var(--muted)',fontWeight:700,marginBottom:2}}>{greet} 👋</p><h1 style={{fontSize:26,fontWeight:900,letterSpacing:'-.03em',marginBottom:6}}>{user?.name?.split(' ')[0]}</h1><p style={{color:'var(--muted)',fontSize:14}}>{user?.goal?'Working towards: '+user.goal:'Complete your AI Skill Scan to get personalised guidance.'}</p></div>
    <div className="g4 fu1" style={{marginBottom:22}}>{[['XP Points',user?.xp||0,'var(--teal)','⚡','rgba(43,158,150,0.08)'],['Level',level,'var(--orange)','🔥','rgba(232,96,26,0.08)'],['Badges',user?.badges?.length||0,'var(--purple)','🏅','rgba(123,108,246,0.08)'],['Progress',pct+'%','var(--green)','📈','rgba(74,158,58,0.08)']].map(([l,v,c,ic,bg])=><div key={l} className="card" style={{padding:'18px 20px',boxShadow:'0 2px 12px rgba(0,0,0,0.04)'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}><span style={{fontSize:11,color:'var(--muted)',fontWeight:700,textTransform:'uppercase',letterSpacing:'0.06em'}}>{l}</span><div style={{width:32,height:32,borderRadius:10,background:bg,display:'flex',alignItems:'center',justifyContent:'center',fontSize:16}}>{ic}</div></div><div style={{fontSize:28,fontWeight:900,letterSpacing:'-.03em',color:c,lineHeight:1}}>{v}</div></div>)}</div>
    <div className="fu2" style={{marginBottom:22,padding:'13px 18px',background:'var(--white)',borderRadius:14,border:'1px solid var(--border)',display:'flex',gap:12,alignItems:'center',boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}}><div style={{width:34,height:34,borderRadius:10,background:'rgba(245,200,66,0.12)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:18,flexShrink:0}}>💡</div><div><span style={{fontSize:11,color:'var(--orange)',fontWeight:900,textTransform:'uppercase',letterSpacing:'0.05em'}}>Today · </span><span style={{fontSize:13.5,color:'var(--muted)'}}>{tip}</span></div></div>
    <div style={{fontSize:11,fontWeight:900,color:'var(--muted2)',textTransform:'uppercase',letterSpacing:'0.07em',marginBottom:12}} className="fu2">Quick Actions</div>
    <div className="g2 fu3" style={{marginBottom:28}}>{QUICK.map(a=><div key={a.label} className="card" onClick={()=>nav(a.path)} style={{cursor:'pointer',display:'flex',gap:14,alignItems:'flex-start',boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}} onMouseEnter={e=>{e.currentTarget.style.transform='translateY(-2px)';e.currentTarget.style.boxShadow='0 8px 24px rgba(0,0,0,0.09)'}} onMouseLeave={e=>{e.currentTarget.style.transform='';e.currentTarget.style.boxShadow='0 2px 10px rgba(0,0,0,0.04)'}}><div style={{width:44,height:44,borderRadius:13,background:a.bg,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}><a.icon size={20} color={a.color}/></div><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:7,marginBottom:3}}><span style={{fontWeight:800,fontSize:14,letterSpacing:'-.01em'}}>{a.label}</span>{a.hot&&<span className="chip chip-o" style={{fontSize:10}}>Start Here</span>}</div><p style={{fontSize:12.5,color:'var(--muted)'}}>{a.desc}</p></div><ChevronRight size={15} color="var(--muted2)" style={{flexShrink:0,marginTop:3}}/></div>)}</div>
    {(!user?.background||!user?.goal)&&<div className="card fu4" style={{background:'rgba(232,96,26,0.04)',borderColor:'rgba(232,96,26,0.2)',display:'flex',alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',gap:12,marginBottom:28}}><div><div style={{fontWeight:800,fontSize:15,marginBottom:3}}>Complete your profile</div><p style={{color:'var(--muted)',fontSize:13}}>Add background & goal for personalised AI analysis.</p></div><button className="btn btn-orange btn-sm" onClick={()=>nav('/analyze')}>Complete Now <ArrowRight size={13}/></button></div>}
    <div style={{fontSize:11,fontWeight:900,color:'var(--muted2)',textTransform:'uppercase',letterSpacing:'0.07em',marginBottom:12}}>Explore Company HQs</div>
    <HQExplorer/>
  </div></AppShell>;
}
