import{useState,useEffect}from'react';import{useAuth}from'../context/AuthContext';import AppShell from'../components/AppShell';import{BarChart,Bar,LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,Cell}from'recharts';import{TrendingUp}from'lucide-react';
const TT=({active,payload,label})=>active&&payload?.length?<div style={{background:'var(--white)',border:'1px solid var(--border)',borderRadius:10,padding:'9px 13px',fontSize:13,fontWeight:700,boxShadow:'0 4px 16px rgba(0,0,0,0.08)'}}><div style={{color:'var(--muted)',marginBottom:3}}>{label}</div><div style={{color:'var(--teal)',fontWeight:900}}>{payload[0].value}{payload[0].name==='avg'?' LPA':'%'}</div></div>:null;
const COLS=['#2B9E96','#E8601A','#7B6CF6','#F5C842','#4A9E3A','#F472B6','#3B82F6','#EF4444'];
export default function Market(){
  const{api}=useAuth();const[data,setData]=useState(null);const[tab,setTab]=useState('skills');
  useEffect(()=>{api('/market').then(setData).catch(()=>{});},[]);
  if(!data)return<AppShell><div style={{display:'flex',alignItems:'center',justifyContent:'center',height:300}}><div className="spinner" style={{width:32,height:32}}/></div></AppShell>;
  const TABS=[['skills','Top Skills'],['industries','Industries'],['companies','Companies'],['salaries','Salary Trend']];
  return<AppShell><div style={{maxWidth:940}}>
    <div className="fu" style={{marginBottom:24}}><div className="eye"><TrendingUp size={11}/>Market Intelligence</div><h2 style={{fontSize:24,fontWeight:900,letterSpacing:'-.03em',marginBottom:4}}>India's live job market.</h2><p style={{color:'var(--muted)',fontSize:14}}>Real data on skills, salaries, industries, and who's hiring.</p></div>
    <div className="fu1" style={{display:'flex',gap:3,marginBottom:26,background:'var(--white)',padding:4,borderRadius:100,width:'fit-content',border:'1px solid var(--border)',boxShadow:'0 2px 8px rgba(0,0,0,0.04)'}}>{TABS.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{padding:'7px 18px',borderRadius:100,border:'none',cursor:'pointer',fontSize:13,fontWeight:800,fontFamily:'Cabinet Grotesk,system-ui',transition:'all .2s',background:tab===id?'var(--ink)':'transparent',color:tab===id?'white':'var(--muted)'}}>{label}</button>)}</div>
    {tab==='skills'&&<div style={{display:'flex',flexDirection:'column',gap:18}} className="fu">
      <div className="card" style={{boxShadow:'0 4px 16px rgba(0,0,0,0.06)'}}><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em',marginBottom:18}}>Skill Demand Score (out of 100)</div><ResponsiveContainer width="100%" height={260}><BarChart data={data.topSkills} layout="vertical" margin={{left:20,right:40}}><XAxis type="number" domain={[0,100]} tick={{fill:'var(--muted2)',fontSize:11}}/><YAxis type="category" dataKey="skill" tick={{fill:'var(--muted)',fontSize:12,fontWeight:700}} width={115}/><Tooltip content={<TT/>}/><Bar dataKey="demand" radius={[0,8,8,0]}>{data.topSkills.map((_,i)=><Cell key={i} fill={COLS[i]||'#2B9E96'}/>)}</Bar></BarChart></ResponsiveContainer></div>
      <div className="g2" style={{gap:12}}>{data.topSkills.map((s,i)=><div key={s.skill} className="card" style={{padding:'14px 17px',display:'flex',alignItems:'center',gap:12,boxShadow:'0 2px 8px rgba(0,0,0,0.04)'}}><div style={{width:10,height:10,borderRadius:'50%',background:COLS[i]||'var(--teal)',flexShrink:0}}/><div style={{flex:1}}><div style={{fontWeight:800,fontSize:13.5,letterSpacing:'-.01em'}}>{s.skill}</div><div style={{fontSize:12,color:'var(--muted)'}}>{s.jobs} jobs open</div></div><div style={{fontWeight:900,color:'var(--teal)',fontSize:12.5,flexShrink:0}}>{s.salary}</div></div>)}</div>
    </div>}
    {tab==='industries'&&<div className="g2 fu" style={{gap:14}}>{data.industries.map(ind=><div key={ind.name} className="card" style={{borderLeft:'3px solid '+ind.color,boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:10}}><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em'}}>{ind.name}</div><span className="chip chip-g" style={{fontSize:11}}>{ind.growth}</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:10}}><span className="chip" style={{fontSize:11}}>📋 {ind.openings}</span><span className="chip" style={{fontSize:11}}>💰 {ind.salary}</span></div><div className="prog"><div className="prog-fill" style={{width:Math.min(parseInt(ind.growth),40)*2.5+'%',background:ind.color}}/></div></div>)}</div>}
    {tab==='companies'&&<div className="card fu" style={{boxShadow:'0 4px 16px rgba(0,0,0,0.06)'}}><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em',marginBottom:16}}>Top Hiring Companies in India</div>{data.topCompanies.map((c,i)=><div key={c.name} style={{display:'flex',alignItems:'center',gap:14,padding:'13px 0',borderBottom:i<data.topCompanies.length-1?'1px solid var(--border)':'none'}}><div style={{width:36,height:36,borderRadius:10,background:'var(--cream2)',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:15,color:'var(--teal)',flexShrink:0}}>{c.name[0]}</div><div style={{flex:1}}><div style={{fontWeight:800,fontSize:14,letterSpacing:'-.01em'}}>{c.name}</div><div style={{fontSize:12.5,color:'var(--muted)'}}>{c.type} · {c.location}</div></div><span className="chip chip-t" style={{fontSize:11,flexShrink:0}}>{c.openings}</span></div>)}</div>}
    {tab==='salaries'&&<div className="card fu" style={{boxShadow:'0 4px 16px rgba(0,0,0,0.06)'}}><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em',marginBottom:4}}>Average Salary Trend — India Tech Sector</div><div style={{fontSize:13,color:'var(--muted)',marginBottom:22}}>Monthly avg (₹ LPA) · last 9 months</div><ResponsiveContainer width="100%" height={280}><LineChart data={data.salaryTrends}><XAxis dataKey="month" tick={{fill:'var(--muted2)',fontSize:11}}/><YAxis domain={[6,11]} tick={{fill:'var(--muted2)',fontSize:11}} tickFormatter={v=>'₹'+v+'L'}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div style={{background:'var(--white)',border:'1px solid var(--border)',borderRadius:10,padding:'9px 13px',fontSize:13,boxShadow:'0 4px 16px rgba(0,0,0,0.08)'}}><div style={{color:'var(--muted)',marginBottom:3}}>{label}</div><div style={{color:'var(--teal)',fontWeight:900}}>₹{payload[0].value} LPA</div></div>:null}/><Line type="monotone" dataKey="avg" stroke="#2B9E96" strokeWidth={3} dot={{fill:'#2B9E96',r:5,strokeWidth:0}} activeDot={{r:7,strokeWidth:0}}/></LineChart></ResponsiveContainer></div>}
  </div></AppShell>;
}
