import{useState}from'react';import{useAuth}from'../context/AuthContext';import AppShell from'../components/AppShell';import toast from'react-hot-toast';import{Map,CheckCircle,AlertCircle}from'lucide-react';
const PC=['#2B9E96','#E8601A','#7B6CF6'];
export default function Roadmap(){
  const{user,api,updateUser}=useAuth();const[goal,setGoal]=useState(user?.goal||'');const[city,setCity]=useState(user?.city||'');const[loading,setLoading]=useState(false);const[roadmap,setRoadmap]=useState(user?.roadmap||null);const[proto,setProto]=useState(false);const[open,setOpen]=useState(0);
  const gen=async()=>{if(!goal)return toast.error('Enter your career goal first.');setLoading(true);try{const data=await api('/roadmap',{method:'POST',body:{goal,city,analysis:user?.skillAnalysis}});setRoadmap(data.roadmap);setProto(!!data.prototypeMode);updateUser({...user,xp:data.xp,badges:data.badges,roadmap:data.roadmap});toast.success('Roadmap ready! +30 XP 🗺️');setOpen(0);}catch(err){toast.error(err.message);}finally{setLoading(false);}};
  return<AppShell><div style={{maxWidth:760}}>
    <div className="fu" style={{marginBottom:24}}><div className="eye"><Map size={11}/>90-Day Roadmap</div><h2 style={{fontSize:24,fontWeight:900,letterSpacing:'-.03em',marginBottom:4}}>Your personalised learning plan.</h2><p style={{color:'var(--muted)',fontSize:14}}>3-phase plan with free NPTEL, Swayam, and Coursera resources.</p></div>
    {!roadmap?<div className="card fu1" style={{boxShadow:'0 4px 20px rgba(0,0,0,0.06)'}}><div style={{display:'grid',gap:16}}><div><label className="lbl">Career goal *</label><input className="inp" placeholder="Get a Data Analyst job in 3 months" value={goal} onChange={e=>setGoal(e.target.value)}/></div><div><label className="lbl">City</label><input className="inp" placeholder="Jaipur" value={city} onChange={e=>setCity(e.target.value)}/></div>{!user?.skillAnalysis&&<div style={{padding:'11px 15px',background:'rgba(232,96,26,0.06)',borderRadius:10,border:'1px solid rgba(232,96,26,0.2)',fontSize:13,color:'var(--muted)'}}>💡 Run an <a href="/analyze" style={{color:'var(--orange)',fontWeight:800}}>AI Skill Scan</a> first for a more personalised plan.</div>}<button className="btn btn-teal" onClick={gen} disabled={loading} style={{width:'fit-content'}}>{loading?<><div className="spinner" style={{borderTopColor:'white'}}/>Generating...</>:<><Map size={15}/>Generate My Plan</>}</button></div></div>
    :<div style={{display:'flex',flexDirection:'column',gap:18}}>
      {proto&&<div style={{display:'flex',alignItems:'center',gap:10,padding:'10px 14px',background:'rgba(245,200,66,0.1)',borderRadius:10,border:'1px solid rgba(245,200,66,0.25)',fontSize:13,color:'#7A6000'}}><AlertCircle size={14}/>Prototype — <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer" style={{fontWeight:800,color:'var(--orange)',textDecoration:'underline'}}>Add free Gemini key</a> for live AI.</div>}
      <div className="card card-teal fu" style={{display:'flex',gap:20,flexWrap:'wrap',alignItems:'center',boxShadow:'0 4px 20px rgba(0,0,0,0.06)'}}><div style={{flex:1}}><div className="chip chip-t" style={{marginBottom:9}}>✅ Plan Ready · +30 XP</div><h3 style={{fontSize:17,fontWeight:900,letterSpacing:'-.02em',marginBottom:7}}>{roadmap.finalOutcome}</h3><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><span className="chip chip-g">{roadmap.expectedSalary}</span><span className="chip">90 days · 3 phases</span></div></div><button className="btn btn-outline btn-sm" onClick={()=>setRoadmap(null)}>Regenerate</button></div>
      <div className="card fu1" style={{padding:'18px 22px',boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}}><div style={{fontSize:11,color:'var(--muted2)',fontWeight:900,textTransform:'uppercase',letterSpacing:'0.06em',marginBottom:16}}>Timeline Overview</div><div style={{display:'flex',position:'relative'}}>{roadmap.phases?.map((ph,i)=><div key={i} style={{flex:1,textAlign:'center',position:'relative'}}><div onClick={()=>setOpen(open===i?-1:i)} style={{width:34,height:34,borderRadius:'50%',background:PC[i],margin:'0 auto 7px',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:14,color:'white',position:'relative',zIndex:2,cursor:'pointer',boxShadow:'0 4px 12px '+PC[i]+'44',transition:'transform .2s'}} onMouseEnter={e=>e.currentTarget.style.transform='scale(1.1)'} onMouseLeave={e=>e.currentTarget.style.transform='scale(1)'}>{i+1}</div>{i<(roadmap.phases.length-1)&&<div style={{position:'absolute',top:17,left:'50%',width:'100%',height:2,background:'var(--border)',zIndex:1}}/>}<div style={{fontSize:11,fontWeight:700,color:PC[i]}}>{ph.weeks}</div><div style={{fontSize:10,color:'var(--muted)',marginTop:2}}>{ph.focus}</div></div>)}</div></div>
      {roadmap.phases?.map((ph,i)=><div key={i} className="card fu2" style={{borderLeft:'3px solid '+PC[i],padding:0,overflow:'hidden',boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}}><div onClick={()=>setOpen(open===i?-1:i)} style={{padding:'18px 22px',cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'space-between',gap:14}}><div style={{display:'flex',gap:12,alignItems:'center'}}><div style={{width:32,height:32,borderRadius:9,background:PC[i]+'14',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:14,color:PC[i],flexShrink:0}}>{i+1}</div><div><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em'}}>{ph.phase}</div><div style={{fontSize:12.5,color:'var(--muted)'}}>{ph.weeks} · {ph.focus}</div></div></div><span className="chip" style={{fontSize:11,color:PC[i],borderColor:PC[i]+'44',background:PC[i]+'10',flexShrink:0}}>{open===i?'▲ Hide':'▼ Show'}</span></div>{open===i&&<div style={{padding:'0 22px 22px',borderTop:'1px solid var(--border)'}}><div style={{margin:'16px 0 12px',padding:'12px 15px',background:PC[i]+'0D',borderRadius:10,border:'1px solid '+PC[i]+'22'}}><div style={{fontSize:11,color:PC[i],fontWeight:900,textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:3}}>🎯 Milestone</div><div style={{fontSize:13.5,fontWeight:700}}>{ph.milestone}</div></div><div style={{marginBottom:14}}><div style={{fontSize:11,color:'var(--muted2)',fontWeight:900,textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:9}}>Tasks</div><div style={{display:'flex',flexDirection:'column',gap:8}}>{ph.tasks?.map((t,ti)=><div key={ti} style={{display:'flex',alignItems:'flex-start',gap:9}}><CheckCircle size={15} color={PC[i]} style={{marginTop:2,flexShrink:0}}/><span style={{fontSize:13.5}}>{t}</span></div>)}</div></div>{ph.resources?.length>0&&<div><div style={{fontSize:11,color:'var(--muted2)',fontWeight:900,textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:9}}>Free Resources</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{ph.resources.map((r,ri)=><div key={ri} className="chip" style={{fontSize:11}}>📚 {r.name} · <span style={{color:PC[i]}}>{r.platform}</span></div>)}</div></div>}</div>}</div>)}
      {roadmap.jobsToApply?.length>0&&<div className="card fu3" style={{boxShadow:'0 2px 10px rgba(0,0,0,0.04)'}}><div style={{fontWeight:800,fontSize:15,letterSpacing:'-.01em',marginBottom:12}}>🎯 Jobs to apply after 90 days</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{roadmap.jobsToApply.map(j=><span key={j} className="chip chip-t">{j}</span>)}</div></div>}
    </div>}
  </div></AppShell>;
}
